export GIT_COMMITTER_NAME="mittsq"
export GIT_COMMITTER_EMAIL="12470297+mittsq@users.noreply.github.com"
export GIT_AUTHOR_NAME="mittsq"
export GIT_AUTHOR_EMAIL="12470297+mittsq@users.noreply.github.com"
export GIT_SSH_COMMAND="ssh -i /data/gitkey"
